# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _OperativeSystems


class _Linux(_OperativeSystems):
    _type = "linux"
    _icon_dir = "resources/operativesystems/linux"


class AmazonLinux(_Linux):
    _icon = "amazon-linux.png"


class Centos(_Linux):
    _icon = "centos.png"


class OracleLinux(_Linux):
    _icon = "oracle-linux.png"


class Redhat(_Linux):
    _icon = "redhat.png"


class Ubuntu(_Linux):
    _icon = "ubuntu.png"


# Aliases
