# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _OperativeSystems


class _Windows(_OperativeSystems):
    _type = "windows"
    _icon_dir = "resources/operativesystems/windows"


# Aliases
