# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Programming


class _Testing(_Programming):
    _type = "testing"
    _icon_dir = "resources/programming/testing"


class Molecule(_Testing):
    _icon = "molecule.png"


# Aliases

molecule = Molecule
